from __future__ import annotations

import json
import subprocess
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True, slots=True)
class GeneratedFile:
    path: str
    content: str


def available_templates() -> list[str]:
    return ["api", "cli", "library", "web"]


def build_project(kind: str, name: str, destination: Path) -> list[Path]:
    kind = kind.lower()
    if kind not in available_templates():
        raise ValueError(f"unknown project type '{kind}'. Available: {', '.join(available_templates())}")
    project_dir = destination / name
    project_dir.mkdir(parents=True, exist_ok=False)
    files = _template(kind, name)
    created: list[Path] = []
    for file in files:
        path = project_dir / file.path
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(file.content, encoding="utf-8")
        created.append(path)
    subprocess.run(["git", "init"], cwd=project_dir, check=False, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    return created


def _template(kind: str, name: str) -> list[GeneratedFile]:
    common = [
        GeneratedFile(".gitignore", "__pycache__/\n.venv/\n.env\nnode_modules/\ndist/\nbuild/\n"),
        GeneratedFile("README.md", f"# {name}\n\nGenerated by Ghost IDE.\n"),
    ]
    if kind == "cli":
        return common + [
            GeneratedFile(
                "pyproject.toml",
                (
                    "[build-system]\nrequires = [\"setuptools>=68\"]\nbuild-backend = \"setuptools.build_meta\"\n\n"
                    f"[project]\nname = \"{name}\"\nversion = \"0.1.0\"\nrequires-python = \">=3.10\"\n\n"
                    f"[project.scripts]\n{name} = \"{name.replace('-', '_')}.__main__:main\"\n\n"
                    "[tool.setuptools.packages.find]\nwhere = [\"src\"]\n"
                ),
            ),
            GeneratedFile(f"src/{name.replace('-', '_')}/__init__.py", ""),
            GeneratedFile(
                f"src/{name.replace('-', '_')}/__main__.py",
                "def main() -> int:\n    print('Hello from your CLI app')\n    return 0\n\n\nif __name__ == '__main__':\n    raise SystemExit(main())\n",
            ),
            GeneratedFile("tests/test_smoke.py", "def test_smoke():\n    assert True\n"),
        ]
    if kind == "library":
        package = name.replace("-", "_")
        return common + [
            GeneratedFile("pyproject.toml", f"[project]\nname = \"{name}\"\nversion = \"0.1.0\"\nrequires-python = \">=3.10\"\n"),
            GeneratedFile(f"src/{package}/__init__.py", "__all__ = ['hello']\n\n\ndef hello() -> str:\n    return 'hello'\n"),
            GeneratedFile("tests/test_library.py", f"from {package} import hello\n\n\ndef test_hello():\n    assert hello() == 'hello'\n"),
        ]
    if kind == "api":
        return common + [
            GeneratedFile("requirements.txt", "fastapi\nuvicorn\n"),
            GeneratedFile("app/main.py", "from fastapi import FastAPI\n\napp = FastAPI()\n\n\n@app.get('/')\ndef root():\n    return {'status': 'ok'}\n"),
            GeneratedFile("run.sh", "uvicorn app.main:app --reload\n"),
        ]
    package_json = {
        "name": name,
        "version": "0.1.0",
        "private": True,
        "scripts": {"dev": "vite --host 0.0.0.0", "build": "vite build", "preview": "vite preview"},
        "dependencies": {"@vitejs/plugin-react": "latest", "vite": "latest", "react": "latest", "react-dom": "latest"},
        "devDependencies": {},
    }
    return common + [
        GeneratedFile("package.json", json.dumps(package_json, indent=2) + "\n"),
        GeneratedFile("index.html", "<div id=\"root\"></div><script type=\"module\" src=\"/src/main.jsx\"></script>\n"),
        GeneratedFile(
            "src/main.jsx",
            "import React from 'react';\nimport { createRoot } from 'react-dom/client';\nimport './style.css';\n\ncreateRoot(document.getElementById('root')).render(<h1>Hello from Ghost IDE</h1>);\n",
        ),
        GeneratedFile("src/style.css", "body { font-family: system-ui, sans-serif; margin: 3rem; }\n"),
    ]

